################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc_ex.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_comp.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cordic.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cortex.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma_ex.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_exti.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_fdcan.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ex.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ramfunc.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_gpio.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_opamp.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_opamp_ex.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr_ex.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc_ex.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim_ex.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart_ex.c \
D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_adc.c 

OBJS += \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_adc.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_adc_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_comp.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_cordic.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_cortex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_exti.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_fdcan.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ramfunc.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_gpio.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_opamp.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_opamp_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_ll_adc.o 

C_DEPS += \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_adc.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_adc_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_comp.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_cordic.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_cortex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_exti.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_fdcan.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ramfunc.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_gpio.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_opamp.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_opamp_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_ll_adc.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_adc.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_adc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_adc_ex.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_adc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_adc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_comp.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_comp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_comp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_cordic.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cordic.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_cordic.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_cortex.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cortex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_cortex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma_ex.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_exti.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_exti.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_exti.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_fdcan.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_fdcan.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_fdcan.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ex.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ramfunc.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ramfunc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ramfunc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_gpio.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_gpio.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_opamp.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_opamp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_opamp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_opamp_ex.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_opamp_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_opamp_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr_ex.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc_ex.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim_ex.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart_ex.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart_ex.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_ll_adc.o: D:/Tatsu/Documents/MotorControl\ Workbench/BLDC_Tension_Control/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_adc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32G431xx -c -I../../../Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/Any/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/MCLib/G4xx/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/UILibrary/Inc -I../../../MCSDK_v5.4.5/MotorControl/MCSDK/SystemDriveParams -I../../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../../Drivers/CMSIS/Include -I../../../Drivers/CMSIS/DSP/Include -O3 -ffunction-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G4xx_HAL_Driver/stm32g4xx_ll_adc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

